### PR TITLE
AppRouter optional param configuration from console

### PR DESCRIPTION
**Pull request by jaimecasero**
This should fix  https://github.com/Mobicents/sip-servlets/issues/6

Also added implementation for issue https://github.com/Mobicents/sip-servlets/issues/5

### CODE REVIEW

**Comment by deruelle** [comment]
I tried locally but when trying to update from the management interface the REGISTER to contain REGEX=From:.*sip:.*@sip-servlets\.com in the Platform-specific field and save I get in the browser console 

Failed to load resource:http://127.0.0.1:8080/jolokia//exec/Sip-Servlets%3Atype%3DSipApplicationDispatcher/updateApplicationRouterConfiguration(java.lang.Object)/REGISTER%3D(%22WebsocketSample%22%2C%22DAR%3AFrom%22%2C%22ORIGINATING%22%2C%22%22%2C%22NO_ROUTE%22%2C%220%22%2C%22REGEX%3DFrom%3A.*sip%3A.*%40sip-servlets%5C.com%22)%0AINVITE%3D(%22WebsocketSample%22%2C%22DAR%3AFrom%22%2C%22ORIGINATING%22%2C%22%22%2C%22NO_ROUTE%22%2C%220%22%2C%22%22)%0AOPTIONS%3D(%22WebsocketSample%22%2C%22DAR%3AFrom%22%2C%22ORIGINATING%22%2C%22%22%2C%22NO_ROUTE%22%2C%220%22%2C%22%22)%0AMESSAGE%3D(%22WebsocketSample%22%2C%22DAR%3AFrom%22%2C%22ORIGINATING%22%2C%22%22%2C%22NO_ROUTE%22%2C%220%22%2C%22%22)%0A the server responded with a status of 400 (Bad Request)

**Comment by deruelle** [comment]
Please note that using DIRECTION=OUTBOUND worked so I think some of the content value can cause issues, can you look into that ?

**Comment by deruelle** [comment]
Also for new files can you update the license header to https://github.com/Mobicents/sip-servlets/wiki/Contribute-to-Mobicents-SIP-Servlets#committing-code ?

**Comment by deruelle** [comment]
Can you also format the code according to https://github.com/Mobicents/sip-servlets/wiki/Contribute-to-Mobicents-SIP-Servlets#code-formatting ?

**Comment by deruelle** [comment]
Also when adding new piece of code, for the most relevant parts we try to add a link to the github issue so it's easy to spot if there is regression, what caused the regression and why the code was introduced. See example with https://github.com/Mobicents/sip-servlets/blob/f77665dfe33bf1f9f247c35c0b94f6e7415eec0a/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/core/dispatchers/SubsequentRequestDispatcher.java#L478

Can you update some of the code you added to do the same ?

**Comment by jaimecasero** [comment]
Hi Jean,
Im back again. I tried the scenario you mentioned, and the results are
different. I see no problem in console, neither 400 response. Could it be a
browser issue?

Regards

**Comment by deruelle** [comment]
No, it's because github badly formatted what I really used. this below is failing:
```
REGEX=From:.*sip:.*@sip-servlets\.com
```

**Comment by jaimecasero** [comment]
reproduced.

we need to take care about encoding this special field in the final URL.
Let me fix it quickly, and i will come back to you.

**Comment by deruelle** [comment]
OK great. Thanks Jaime.

**Comment by deruelle** [comment]
Thanks @jaimecasero. The encoding in the special field is fixed however the Platform-Specific :  field is not loaded from the file, ie if I enter a value in the field, save changes by clicking Apply Changes button and reload the page, the field is blank

**Comment by jaimecasero** [comment]
Jean, you may test my changes at http://108.59.86.38:8080/sip-servlets-management/#. I will be using this vm hosted by google for my own int testing...

**Comment by jaimecasero** [comment]
Jean, as you can see i merged all the commits from Mobicents/master into my own fork to check no conflicts were there. Please let me know if this is causing any issue

**Comment by deruelle** [comment]
Thanks @jaimecasero. Now all is working. I merged it to master.

**Pull request merged**
